# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cd25de8ede64997dd7b0061d8f97cd35ad6f52ecf7593b519c5a528ba8e0e959757c33c2b4a0d7241ab10e250f10cdbee562179e7520b2e4e72405d91899ff09

test:
  secret_key_base: f7a49e1f93cad6f24dd0ee974a74b6f6e5e3d6d2ccfbd2804bb6c1d70d40a1417f1e765a52b78b52e9c72a4bc6e9a6313f1780a39b31eda88ce1a77f5445b8ff

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
